# Generated by Django 6.0.6 on 2026-06-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='reg',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
