# Generated by Django 6.0.6 on 2026-06-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_student_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='decorator',
            name='API_Path',
            field=models.CharField(default=0.000499001996007984, max_length=500),
            preserve_default=False,
        ),
    ]
