# Generated by Django 6.0.6 on 2026-06-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='split_members',
            name='payment_status',
            field=models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit'), ('SPLIT_PAYMENT', 'Split Payment'), ('SETTLEMENT_ADJUSTMENT', 'Settlement Adjustment'), ('SPLIT_CREATED', 'Split Created')], default='PENDING', max_length=100),
        ),
    ]
