# Generated by Django 6.0.6 on 2026-06-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0003_netbalance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='netbalance',
            name='updated_at',
        ),
        migrations.AddConstraint(
            model_name='netbalance',
            constraint=models.UniqueConstraint(fields=('debtor', 'creditor'), name='unique_debtor_creditor'),
        ),
    ]
