# Generated by Django 6.0.6 on 2026-06-25 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='split',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('description', models.TextField()),
                ('Split_type', models.CharField(choices=[('EQUAL', 'Equal'), ('CUSTOM', 'Custom')], default='EQUAL', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=100)),
            ],
            options={
                'db_table': 'splits',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=100)),
                ('split', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='splitv2.split')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to='splitv2.user')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to='splitv2.user')),
            ],
            options={
                'db_table': 'settlements',
            },
        ),
        migrations.CreateModel(
            name='transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('Transactions_type', models.CharField(choices=[('TRANSFER', 'Transfer'), ('SPLIT_PAYMENT', 'Split Payment'), ('WALLET_PAYMENT', 'Wallet Payment')], max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='splitv2.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='splitv2.user')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='split_Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_status', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit'), ('SPLIT_PAYMENT', 'Split Payment'), ('SETTLEMENT_ADJUSTMENT', 'Settlement Adjustment'), ('SPLIT_CREATED', 'Split Created'), ('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=100)),
                ('Joined_at', models.DateTimeField(auto_now_add=True)),
                ('split', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='splitv2.split')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='splitv2.user')),
            ],
            options={
                'db_table': 'split_members',
            },
        ),
        migrations.AddField(
            model_name='split',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Created_splits', to='splitv2.user'),
        ),
        migrations.CreateModel(
            name='SettlementLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('SPLIT_CREATED', 'Split Created'), ('PAYMENT', 'Payment'), ('NET_OFFSET', 'Net Offset'), ('PARTIAL_OFFSET', 'Partial Offset')], max_length=50)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, default='')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='splitv2.settlement')),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_creditor', to='splitv2.user')),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_debtor', to='splitv2.user')),
            ],
            options={
                'db_table': 'settlement_ledger',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='wallets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='splitv2.user')),
            ],
            options={
                'db_table': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='NetBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='splitv2.user')),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='splitv2.user')),
            ],
            options={
                'db_table': 'net_balances',
                'constraints': [models.UniqueConstraint(fields=('debtor', 'creditor'), name='unique_debtor_creditor')],
            },
        ),
    ]
