# Generated by Django 6.0.6 on 2026-06-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitv2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Transactions_type',
            field=models.CharField(choices=[('TRANSFER', 'Transfer'), ('SPLIT_PAYMENT', 'Split Payment'), ('WALLET_PAYMENT', 'Wallet Payment'), ('WALLET_TOPUP', 'Wallet Topup'), ('EXPENSE', 'Expense')], max_length=100),
        ),
    ]
